### ISSUE TITLE
为何最近发的帖子不显示在首页呢？

### ISSUE THREAD

**Issue by luckypoem** [chingli/rockrock#1]
你好。
我克隆了这个源码https://github.com/scottcwilson/hugosite ，并且克隆了你的代码到其themes目录，不过装好后，为何最近发的帖子不显示在首页呢？
http://swgi.bright.biz.st/
http://swgi.bright.biz.st/post/test-2/ 和http://swgi.bright.biz.st/post/test-1/ 并不显示在首页。为什么？如何解决？

**Comment by chingli** [comment]
@luckypoem 应该是 hugo 升级后导致的不兼容，稍后就修正，并替换掉多说。

**Comment by chingli** [comment]
我自己试了试，主题没有问题，你把原来正常显示的任一篇博客文章复制一个，重新命名，只改变里面的 date 为当前日期，看看能不能再首页显示。
